name = "no-signal-store"
compatibility_date = "2026-09-29"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "no-signal-db"
database_id = "abc69744-c68d-4dda-821e-a177764bd2e9"
